### ISSUE TITLE
invalid argument at pathToArray (node_modules\memory-fs\lib\MemoryFileSystem.js:44:10)

### ISSUE THREAD

**Issue by se8820726** [vuexpress/vuexpress#3]
I followed your guide for using vueexpress as template engine of expressjs

now I gave this error when went to url : http://localhost/

```
Error: invalid argument
    at pathToArray (node_modules\memory-fs\lib\MemoryFileSystem.js:44:10)
    at MemoryFileSystem.readFileSync (node_modules\memory-fs\lib\MemoryFileSystem.js:103:13)
    at MemoryFileSystem.<computed> [as readFile] (node_modules\memory-fs\lib\MemoryFileSystem.js:300:34)
    at node_modules\@doweb\vuexpress\lib\renderer\compiler.js:194:15
    at new Promise (<anonymous>)
    at node_modules\@doweb\vuexpress\lib\renderer\compiler.js:153:85
    at Array.map (<anonymous>)
    at node_modules\@doweb\vuexpress\lib\renderer\compiler.js:153:69
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by varunkumarmedam** [comment]
I too got the same issue

**Comment by se8820726** [comment]
I finally decided that it was best to use [vue cli](https://cli.vuejs.org/).

This allows multiple features including the automatic installation of vueexpress

**Comment by varunkumarmedam** [comment]
@se8820726 yaa but app need to be build for publishing, my need is based on using cdn only
